title: ben andrew
position: apprentice
affiliation: ccbs, carney institute
email: benjamin_andrew@brown.edu
avatar: ./assets/img/benwandrew.png
favicon: ./assets/img/benwandrew.png
favicon_dark: ./assets/img/benwandrew.png
remote_theme: yaoyao-liu/minimal-light
